MODEL:
  NAME: transformer
  DEVICE_ID: ('0')
  DEVICE: 'cuda'
  PRETRAIN_PATH: ./pretrain/abc.ptk

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]

DATASETS:
  NAMES: market1501
  ROOT_DIR: ./data

DATALOADER:
  NUM_WORKERS: 2

SOLVER:
  OPTIMIZER_NAME: 'ADAM'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  SEED: 1
  CHECKPOINT_PATH: /kaggle/input/myckpt/transformer_checkpoint_epoch_29_acc_0.1642.ckpt
  RESUME_TRAINING: False

TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: '/kaggle/working/LW-Transformer/saved_weights'